CREATE TABLE HABITAT
(
  HabitatID INT NOT NULL,
  HabitatName VARCHAR2(50) NOT NULL,
  ClimateType VARCHAR2(50) NOT NULL,
  MaxCapacity INT NOT NULL CHECK (MaxCapacity > 0),
  PRIMARY KEY (HabitatID)
);

CREATE TABLE SPECIES
(
  SpeciesID INT NOT NULL,
  CommonName VARCHAR2(50) NOT NULL,
  ScientificName VARCHAR2(50) NOT NULL,
  ConservationStatus VARCHAR2(50) NOT NULL,
  PRIMARY KEY (SpeciesID)
);

CREATE TABLE DIETPLAN
(
  DietPlanID INT NOT NULL,
  PlanName VARCHAR2(50) NOT NULL,
  DailyCost NUMERIC(6,2) NOT NULL CHECK (DailyCost >= 0),
  PRIMARY KEY (DietPlanID)
);

CREATE TABLE ANIMAL
(
  AnimalID INT NOT NULL,
  Name VARCHAR2(50) NOT NULL,
  DateOfBirth DATE NOT NULL,
  Gender VARCHAR2(50) NOT NULL,
  HabitatID INT NOT NULL,
  SpeciesID INT NOT NULL,
  DietPlanID INT NOT NULL,
  PRIMARY KEY (AnimalID),
  FOREIGN KEY (HabitatID) REFERENCES HABITAT(HabitatID),
  FOREIGN KEY (SpeciesID) REFERENCES SPECIES(SpeciesID),
  FOREIGN KEY (DietPlanID) REFERENCES DIETPLAN(DietPlanID)
);

CREATE TABLE HEALTHRECORD
(
  RecordID INT NOT NULL,
  CheckupDate DATE NOT NULL,
  Weight NUMERIC(6,2) NOT NULL CHECK (Weight > 0),
  HealthStatus VARCHAR2(50) NOT NULL,
  AnimalID INT NOT NULL,
  PRIMARY KEY (RecordID),
  FOREIGN KEY (AnimalID) REFERENCES ANIMAL(AnimalID)
);

CREATE TABLE DAILYFEEDING
(
  FeedingID INT NOT NULL,
  FeedingDate DATE NOT NULL,
  FoodConsumedQty NUMERIC(5,2) NOT NULL CHECK (FoodConsumedQty >= 0),
  AnimalID INT NOT NULL,
  PRIMARY KEY (FeedingID),
  FOREIGN KEY (AnimalID) REFERENCES ANIMAL(AnimalID)
);