-- Script for integrating the veterinary clinic system into the existing zoo database.

-- 1. Creating new department tables
CREATE TABLE VETERINARIAN (
    VetID INTEGER PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    LicenseNumber VARCHAR(50) UNIQUE NOT NULL,
    Specialization VARCHAR(100),
    HireDate DATE NOT NULL CHECK (HireDate <= CURRENT_DATE)
);

CREATE TABLE MEDICALVISIT (
    VisitID INTEGER PRIMARY KEY,
    VisitDate DATE NOT NULL CHECK (VisitDate <= CURRENT_DATE),
    Reason VARCHAR(255) NOT NULL,
    Summary TEXT,
    Cost NUMERIC(10,2) CHECK (Cost >= 0),
    AnimalID INTEGER NOT NULL,
    VetID INTEGER NOT NULL
);

CREATE TABLE TREATMENT (
    TreatmentID INTEGER PRIMARY KEY,
    Description VARCHAR(255) NOT NULL,
    Duration VARCHAR(50),
    Type VARCHAR(50),
    Severity VARCHAR(50) CHECK (Severity IN ('Low', 'Medium', 'High', 'Critical'))
);

CREATE TABLE MEDICATION (
    MedID INTEGER PRIMARY KEY,
    CommercialName VARCHAR(100) NOT NULL,
    ActiveIngredient VARCHAR(255),
    DosageUnit VARCHAR(50),
    ExpirationDate DATE NOT NULL CHECK (ExpirationDate >= '2020-01-01')
);

CREATE TABLE VACCINATION (
    VacID INTEGER PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Manufacturer VARCHAR(100),
    FrequencyMonths INTEGER CHECK (FrequencyMonths > 0),
    StorageTemp VARCHAR(50)
);

CREATE TABLE MIRSHAM_VISIT_TREATMENT (
    VisitID INTEGER NOT NULL,
    TreatmentID INTEGER NOT NULL,
    PRIMARY KEY (VisitID, TreatmentID)
);

CREATE TABLE HERGEL_TREATMENT_MEDICATION (
    TreatmentID INTEGER NOT NULL,
    MedID INTEGER NOT NULL,
    PRIMARY KEY (TreatmentID, MedID)
);

CREATE TABLE TREATMENT_VACCINATION (
    TreatmentID INTEGER NOT NULL,
    VacID INTEGER NOT NULL,
    PRIMARY KEY (TreatmentID, VacID)
);

-- 2. ALTER table commands for integration with the existing database
-- Linking medical visits to our existing animals table and the new veterinarians table
ALTER TABLE MEDICALVISIT ADD CONSTRAINT fk_visit_animal FOREIGN KEY (AnimalID) REFERENCES ANIMAL(AnimalID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MEDICALVISIT ADD CONSTRAINT fk_visit_vet FOREIGN KEY (VetID) REFERENCES VETERINARIAN(VetID) ON DELETE CASCADE ON UPDATE CASCADE;

-- Foreign keys for the linking tables of the new department
ALTER TABLE MIRSHAM_VISIT_TREATMENT ADD CONSTRAINT fk_mirsham_visit FOREIGN KEY (VisitID) REFERENCES MEDICALVISIT(VisitID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MIRSHAM_VISIT_TREATMENT ADD CONSTRAINT fk_mirsham_treatment FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE HERGEL_TREATMENT_MEDICATION ADD CONSTRAINT fk_hergel_treatment FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE HERGEL_TREATMENT_MEDICATION ADD CONSTRAINT fk_hergel_medication FOREIGN KEY (MedID) REFERENCES MEDICATION(MedID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TREATMENT_VACCINATION ADD CONSTRAINT fk_tv_treatment FOREIGN KEY (TreatmentID) REFERENCES TREATMENT(TreatmentID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TREATMENT_VACCINATION ADD CONSTRAINT fk_tv_vaccination FOREIGN KEY (VacID) REFERENCES VACCINATION(VacID) ON DELETE CASCADE ON UPDATE CASCADE;

-- Adding an index to improve performance of common queries
CREATE INDEX idx_medicalvisit_animal ON MEDICALVISIT(AnimalID);
